Various modifications :
SalimDr/adal-angular5 pull request #2
Opened 2019-12-10 09:51 UTC by sancho0410

- Add callback when token expire

2019-12-10 12:28 UTC, Macadoshis requested changes

2019-12-10 12:28 UTC, Macadoshis commented on dist/adal5.service.d.ts
> +    private doRefresh;
`private doRefresh : () => Promise<boolean>;`

2019-12-10 12:28 UTC, Macadoshis commented on dist/adal5.service.d.ts
> +    private updateDataFromCache;
pourquoi ces changes de signatures ?

2019-12-10 12:28 UTC, Macadoshis commented on dist/adal5.service.js
> +var Adal5Service = /** @class */ (function () {
revert

2019-12-10 12:28 UTC, Macadoshis commented on dist/adal5.service.js
> +            this.doRefresh = function () { return Promise.resolve(true); };
to typescript :  `this.doRefresh = () => Promise.resolve(true);`

2019-12-10 12:28 UTC, Macadoshis commented on dist/adal5.service.js
>   * @export
pourquoi le .js a été commité ??

2019-12-10 12:28 UTC, Macadoshis commented on src/adal5.service.ts
> +import {adal} from 'adal-angular';
![image](https://user-images.githubusercontent.com/2878861/70527030-35f57f80-1b4b-11ea-9e43-07b2f8be3c50.png)
et refais ctrl-alt-L / ctrl-alt-O

2019-12-10 12:28 UTC, Macadoshis commented on src/adal5.service.ts
> +      this.doRefresh = () => Promise.resolve(true);
donc c'est pour gérer le cas où lors du 1er chargement l'user n'est pas du tout connecté ?

dans ce cas vu que tu écrases le `configOptions.doRefresh` assigné en ligne 74, dès lors la connection établie il n'y a plus le bahavior souhaité ?

ou bien est-ce que quand on rentre en ligne 85, c'est forcément un cas qui va faire un refresh de l'écran (window.location.reload) ? si oui, ce cas ne marchera pas dans le cas d'un AdalCOnfig en mode popUp:true

2019-12-10 12:28 UTC, Macadoshis commented
ne pas commiter le dist/

2019-12-10 13:21 UTC, sancho0410 commented on dist/adal5.service.d.ts
> +    private updateDataFromCache;
c'est de l'auto lors de la compil probablement

2019-12-10 13:22 UTC, sancho0410 commented on dist/adal5.service.js
> +            this.doRefresh = function () { return Promise.resolve(true); };
le js est auto compile, le modifier n'est pas forcement une bonne idee

2019-12-10 13:38 UTC, sancho0410 commented on dist/adal5.service.d.ts
> +    private doRefresh;
c'est dans le dossier dist/, donc a revert non ?

2019-12-10 13:47 UTC, sancho0410 commented on src/adal5.service.ts
> +      this.doRefresh = () => Promise.resolve(true);
En gros si l'utilisateur n'est plus authentifié, on ne passe plus par la popin et on refais le circuit d'authen, sachant qu'on repasse dans l'init

2019-12-11 16:47 UTC, Macadoshis requested changes

2019-12-11 16:47 UTC, Macadoshis commented on src/adal5.service.ts
> +      this.doRefresh = () => Promise.resolve(true);
pourquoi on écrase `doRefresh` en cas d'erreur ?

2019-12-11 16:47 UTC, Macadoshis commented on src/adal5.service.ts
> +      this.doRefresh = () => Promise.resolve(true);
il faudrait par ex. un mécanisme de retry, et au bout de N catch, on l'écrase vraiment sinon on continue à le conserver à sa valeur de doRefreshOption

2019-12-11 16:47 UTC, Macadoshis commented on src/adal5.service.ts
> +  private doRefreshOption: () => Promise<boolean>;
pas las peine de l'initialiser (redondant avec l.78), ou sinon au moins l'initialiser à `private doRefreshOption: () => this.doRefresh;`

2019-12-12 06:38 UTC, sancho0410 commented on src/adal5.service.ts
> +      this.doRefresh = () => Promise.resolve(true);
non justement dans le catch on le force à bypass la fonction de refresh, sachant que le clean force la reconnexion, dans ce cas on souhaite se reconnecter sans avoir le resultat de l'appel à la fonction de refresh

2019-12-13 11:08 UTC, merged